admin/src/web/controllers/payments.py
from flask import Blueprint, render_template, request, redirect, url_for, flash

from src.core import setting
from src.core import payments
from src.web.helpers.auth import token_required, user_has_permission
from src.core.quotas.quotaV2 import (
    Quota,
    get_quota_by_id,
    get_quotas,
    QuotaJson,
    get_detail_quota,
    assign_payment,
)
from src.core import payments, associates
import json
from datetime import datetime


payment_blueprint = Blueprint("payments", __name__, url_prefix="/pagos")


@payment_blueprint.get("/<int:num>")
@token_required
@user_has_permission("quota_index")
def payment_index_page(num):
    # Trae asociados paginadas.
    payments_list = payments.list_payments_page(
        num, setting.get_setting().cant_elements_page
    )
    return render_template(
        "payments/payments.html",
        payments=payments_list,
        currency=setting.get_setting().currency_type,
    )


@payment_blueprint.get("/new_payment/<int:current_page>")
@token_required
@user_has_permission("quota_new")
def new_payment(current_page):
    associates_list = associates.list_associated()
    return render_template(
        "payments/new_payment.html",
        associates=associates_list,
        quotas=[],
        selected=0,
        return_page=current_page,
    )


@payment_blueprint.post("/new_payment/<int:current_page>/filtrar")
@token_required
@user_has_permission("quota_new")
def filtrar_quotas(current_page):
    params = request.form
    associated_id = int(params["selectAsociado"])
    associates_list = associates.list_associated()
    quotas_list = []
    quotas = get_quotas()
    for i in quotas:
        if i.associated_id == associated_id and i.state == False:
            quota_parsed = QuotaJson.fromJSON(i.dataJSON)
            i.final_amount = quota_parsed.total_amount
            if i.end_date < datetime.now():
                amount_extra = quota_parsed.surcharge * quota_parsed.total_amount / 100
                i.final_amount = i.final_amount + amount_extra
            quotas_list.append(i)
    return render_template(
        "payments/new_payment.html",
        associates=associates_list,
        quotas=quotas_list,
        selected=associated_id,
        return_page=current_page,
    )


@payment_blueprint.get("/new_payment/<int:current_page>/pagar/<int:quotaId>")
@token_required
@user_has_permission("quota_new")
def pagar(current_page, quotaId):
    quota = get_quota_by_id(quotaId)
    quota_detail = get_detail_quota(quotaId)
    overdue_fee = quota.end_date > datetime.now()
    amount_extra = quota_detail.surcharge * quota_detail.total_amount / 100
    return render_template(
        "payments/payment_pay.html",
        current_page=current_page,
        quota=quota_detail,
        id_quota=quotaId,
        overdue_fee=overdue_fee,
        amount_extra=amount_extra,
    )


@payment_blueprint.post("/new_payment/<int:current_page>/pagar/<int:quotaId>")
@token_required
@user_has_permission("quota_new")
def pagar_post(current_page, quotaId):
    quota_from_db = get_quota_by_id(quotaId)
    if quota_from_db.state:
        flash("La cuota ya esta pagada")
        return redirect(url_for("payments.payment_index_page", num=current_page))
    quota_parsed = QuotaJson.fromJSON(quota_from_db.dataJSON)
    if quota_from_db.end_date < datetime.now():
        amount_extra = quota_parsed.surcharge * quota_parsed.total_amount / 100
        quota_parsed.total_amount = quota_parsed.total_amount + amount_extra
    payment = payments.add_payment(
        orden=quota_from_db.id + 1000, 
        amount=quota_parsed.total_amount,
        state=True
    )
    assign_payment(quota_from_db, payment)
    flash("Se registro el pago correctamente", "success")
    return redirect(url_for("payments.payment_index_page", num=current_page))


@payment_blueprint.post("/filtrar/<int:current_page>")
@token_required
@user_has_permission("quota_index")
def filtrar(current_page):
    # Filtra la lista de pagos segun el numero de socio o apellido.
    params = request.form
    if params["id"] != "" and int(params["id"]) > 0:
        payments_list = payments.find_payment_by_id(
            int(params["id"]), setting.get_setting().cant_elements_page, current_page
        )
        if not payments_list.items:
            flash(
                f"No se encuentra pagos del asociado con numero de socio: {params['id']}",
                "error",
            )
            return redirect(url_for("payments.payment_index_page", num=1))
        return render_template("payments/payments.html", payments=payments_list)
    if params["surname"] != "":
        payments_list = payments.find_payment_by_surname(
            params["surname"], setting.get_setting().cant_elements_page, current_page
        )
        if not payments_list.items:
            flash(f"No se encuentra pagos del asociado: {params['surname']}", "error")
            return redirect(url_for("payments.payment_index_page", num=1))
        return render_template("payments/payments.html", payments=payments_list)

    return redirect(url_for("payments.payment_index_page", num=1))


@payment_blueprint.get("/detail/<int:current_page><int:payment_id>")
@token_required
@user_has_permission("quota_show")
def recibo(current_page, payment_id):
    payment = payments.get_payment_by_id(payment_id)
    currency_type = QuotaJson.fromJSON(payment.quotas[0].dataJSON).currency_type
    return render_template(
        "payments/payment_detail.html",
        currency_type=currency_type,
        current_page=current_page,
        payment=payment,
        title=setting.get_setting().voucher_title,
    )

@payment_blueprint.get("/pending_payments/<int:current_page>")
@token_required
@user_has_permission("quota_new")
def pending_payments(current_page):
    pending_payments_list = payments.get_pending_payments()
    empty = True
    for _ in pending_payments_list:
        empty = False
        break
    return render_template(
        "payments/pending_payments.html",
        return_page=current_page,
        pending_payments=pending_payments_list,
        empty=empty
    )

@payment_blueprint.post("/pending_payments/<int:current_page>/<int:pagoId>")
@token_required
@user_has_permission("quota_new")
def aprobar_pago(current_page, pagoId):
    current_payment = payments.get_payment_by_id(pagoId)
    print(current_payment.amount)
    payments.confirm_payment(current_payment)
    flash("Se registro el pago correctamente", "success")
    return redirect(url_for("payments.payment_index_page", num=current_page))

@payment_blueprint.post("/pending_payments/rechazar/<int:current_page>/<int:pagoId>")
@token_required
@user_has_permission("quota_new")
def rechazar_pago(current_page, pagoId):
    current_payment = payments.get_payment_by_id(pagoId)
    payments.decline_payment(current_payment)
    flash("Se rechazo el pago", "success")
    return redirect(url_for("payments.payment_index_page", num=current_page))

admin/src/web/templates/payments/new_payment.html
{% extends 'layout.html' %}
{% set active_page = "pagos" %}
{% block css %}
<link rel="stylesheet" href="{{ url_for('static',filename='css/payments.css') }}">
{% endblock %}
{% block title %}
<title>Nuevo Pago</title>
{% endblock %}

{% block nav %}
{{super()}}
{% endblock %}
{% block content %}

<form class="new-payment" action="{{ url_for('payments.filtrar_quotas',current_page=return_page)}}" method="POST">
    <label for="selectAsociado">Seleccione un asociado</label>
    <select name="selectAsociado" id="selectAsociado">
        {% for a in associates %}
        {% if selected == a.id %}
        <option selected value="{{a.id}}">{{a.name}},{{a.surname}} #{{a.id}}</option>
        {% else %}
        <option value="{{a.id}}">{{a.name}},{{a.surname}} #{{a.id}}</option>
        {% endif %}
        {% endfor %}
    </select>
    <button type="submit">Buscar</button>
</form>

<br>

{% if selected %}
{% if quotas %}
<ul class="quotas-list">
    {% for q in quotas %}
    <li>
        <p>Fecha: {{q.end_date.strftime('%d-%m-%Y')}}, Monto:{{q.final_amount}}</p><a
            href="{{ url_for('payments.pagar_post', current_page=return_page, quotaId=q.id) }}">Pagar</a>
    </li>
    {% endfor %}
</ul>
{% else %}
<h1 style="margin-left: 20px;margin-bottom: 20px;color: white;">No tiene cuotas pendientes</h1>
{% endif %}
{% endif %}


<a class="btn-nuevo-pago" style="margin-left: 20px;"
    href="{{ url_for('payments.payment_index_page', num=return_page) }}">Volver</a>

{% endblock %}

admin/src/web/templates/payments/payment_detail.html
{% extends 'layout.html' %}
{% set active_page = "pagos" %}
{% block css %}
<link rel="stylesheet" href="{{ url_for('static',filename='css/payments.css') }}">
{% endblock %}
{% block title %}
<title>Detalle Pago</title>
{% endblock %}

{% block nav %}
{{super()}}
{% endblock %}
{% block content %}

<div id="recibo" class="recibo-pdf">
    <h1>{{title}}</h1>
    <small># de Recibo {{payment.id}}</small>  
    <p>Se recibio de {{payment.quotas[0].associates.name}} {{payment.quotas[0].associates.name}} <br>
        el importe de {{payment.amount}} {{currency_type}} por el concepto de la couta <br>
        societaria correspondiente a la fecha <b id="month_info">{{payment.quotas[0].end_date.strftime('%d-%m-%Y')}}</b>
    </p>
</div>

<a class="btn-nuevo-pago" style="margin-left: 20px;" href="{{ url_for('payments.payment_index_page', num=current_page) }}">Volver</a>
<button class="btn-nuevo-pago" style="background-color: grey;" onclick="javascript:downloadVoucher();">Descargar</button>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.4.1/jspdf.debug.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/0.4.1/html2canvas.js"></script>
<script>
    function downloadVoucher() {

        const recibo = document.getElementById('recibo');
        const monthInfo = document.getElementById('month_info').innerText

        html2canvas(recibo, {
            onrendered: function (canvasObj) {
                var pdf = new jsPDF({
                    orientation: "landscape",
                    unit: "in",
                    format: [8, 4]
                }),
                    pdfConf = {
                        pagesplit: false,
                        backgroundColor: '#FFF'
                    };
                document.body.appendChild(canvasObj); //appendChild is required for html to add page in pdf
                pdf.addHTML(canvasObj, 0, 0, pdfConf, function () {
                    document.body.removeChild(canvasObj);
                    //pdf.addPage();
                    pdf.save(`recibo-${monthInfo}.pdf`);
                    window.location.reload()
                });
            }
        });
    }

</script>

{% endblock %}

admin/src/web/templates/payments/payment_pay.html
{% extends 'layout.html' %}
{% set active_page = "pagos" %}
{% block css %}
<link rel="stylesheet" href="{{ url_for('static',filename='css/payments.css') }}">
{% endblock %}
{% block title %}
<title>Realizar Pago</title>
{% endblock %}

{% block nav %}
{{super()}}
{% endblock %}
{% block content %}

<form class="recibo" action="{{ url_for('payments.pagar_post',quotaId=id_quota,current_page=current_page)}}" method="POST">
    <label for="#recibo"># de Recibo</label>
    <input name="#recibo" type="text" value="{{id_quota}}" disabled>
    <br>
    <label for="membresia">Membresia:</label>
    <input type="text" value="{{quota.membership_amount}} {{quota.currency_type}}" disabled>
    <br>
    <label>Disciplinas:</label>
    <ul>
        {% for s in quota.sports %}
            <li>{{s.Name}}: <input type="text" value="{{s.monthly_fee}} {{quota.currency_type}}" disabled></li>
        {% endfor %}
    </ul>
    <br>
    {% if overdue_fee %}
        <label for="membresia">Recargo:</label>
        <input type="text" value="{{amount_extra}} {{quota.currency_type}}" disabled>
        <br>
    {% endif %}


    <label for="monto">Monto Total:</label>
    {% if is_defaulter %}
        <input name="monto" type="text" value="{{quota.total_amount + amount_extra}} {{ quota.currency_type }}" disabled>
    {% else %}
        <input name="monto" type="text" value="{{quota.total_amount}} {{ quota.currency_type }}" disabled>
    {% endif %}
    <br>


    <button type="submit">Realizar Pago</button>
</form>


<a class="btn-nuevo-pago" style="margin-left: 20px;" href="{{ url_for('payments.new_payment',current_page=current_page)}}">Volver</a>

<script>
    function pagar() {
        const value = document.getElementById('selectQuota').value;
        console.log("hola")
    }
</script>

{% endblock %}

admin/src/web/templates/payments/payments.html
{% extends 'layout.html' %}
{% set active_page = "payments" %}
{% block css %}
<link rel="stylesheet" href="{{ url_for('static',filename='css/payments.css') }}">
{% endblock %}
{% block liks %}
<script src="https://kit.fontawesome.com/e480f6dd1b.js" crossorigin="anonymous"></script>
{% endblock %}
{% block title %}
<title>Pagos</title>
{% endblock %}

{% block content %}

<table class="tabla">
    <caption>
        <div class="div-titulo-buscar">
            <h1 class="nom-pagina">Pagos:</h1>
            <div class="div-buscar">
                <form class="buscar" action="{{ url_for('payments.filtrar', current_page = payments.pages)}}"
                    method="POST">
                    <input class="buscar_num_asso" type="number" name="id" placeholder="# socio">
                    <input class="buscar_apellido" name="surname" placeholder="Ingrese el apellido">
                    <button class="boton-filtrar" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
                </form>
            </div>
        </div>
    </caption>
    <thead>
        <tr>
            <th># Orden</th>
            <th class="numSocio"># Socio</th>
            <th class="nomAsso">Nombre y Apellido</th>
            <th>Monto</th>
            <th>Fecha</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% if payments.items %}
        {% for payment in payments.items %}
        <tr>
            <td>{{ payment.orden }}</td>
            <td class="numSocio">{{ payment.quotas[0].associated_id }}</td>
            <td>{{ payment.quotas[0].associates.surname}}, {{ payment.quotas[0].associates.name }}</td>
            <td>{{ payment.amount }}</td>
            <td>{{ payment.date.strftime('%d-%m-%Y') }}</td>
            <td><a class="btn btn-detalle"
                    href="{{ url_for('payments.recibo',current_page=payments.page,payment_id=payment.id) }}">Ver
                    detalle</a></td>
        </tr>
        {% endfor %}
        {% else %}
        <td></td>
        <td>Sin pagos</td>
        <td></td>
        <td></td>
        {% endif %}
    </tbody>
</table>
<div class="paginacion">
    <ul>
        {% if payments.has_prev %}
        <li>
            <a href="{{ url_for('payments.payment_index_page', num=payments.prev().page) }}"><i
                    class="fas fa-chevron-left"></i></a>
        </li>
        {% endif %}
        {% for page_num in range(payments.pages) %}
        {% if page_num + 1 > payments.page - 3 and page_num + 1 < payments.page + 3 %} {% if page_num + 1==payments.page
            %} <li>
            <a class="active">{{page_num + 1}}</a>
            </li>
            {% else %}
            <li>
                <a href="{{ url_for('payments.payment_index_page', num=page_num + 1) }}">{{page_num + 1}}</a>
            </li>
            {% endif %}
            {% endif %}
            {% endfor %}
            {% if payments.has_next %}
            <li>
                <a href="{{ url_for('payments.payment_index_page', num=payments.next().page) }}">
                    <i class="fas fa-chevron-right"></i></a>
            </li>
            {% endif %}
    </ul>
</div>

<a class="btn-nuevo-pago" href="{{ url_for('payments.new_payment',current_page=payments.page)}}">Realizar Pago</a>
<a class="btn-nuevo-pago" href="{{ url_for('payments.pending_payments',current_page=payments.page)}}">Pagos Pendientes</a>
{% if email_has_permission(session["user"],"quota_generate") %}
<a class="btn-act-quota" href="{{ url_for('quotas.quota_generate') }}">Actualizar cuotas</a>
{% endif %}

{% endblock %}

admin/src/web/templates/payments/pending_payments.html
{% extends 'layout.html' %}
{% set active_page = "pagos" %}
{% block css %}
<link rel="stylesheet" href="{{ url_for('static',filename='css/payments.css') }}">
{% endblock %}
{% block title %}
<title>Pagos Pendientes</title>
{% endblock %}

{% block nav %}
{{super()}}
{% endblock %}
{% block content %}

{% if pending_payments %}
    <ul class="quotas-list">
        {% for p in pending_payments %}
        <li>
            <p>Nro Orden: {{p.orden}}, Monto:{{p.amount}}</p>
            <div id="image{{p.orden}}" style="display: none;" class="voucher_view">
                <img src="{{ 'https://admin-grupo17.proyecto2022.linti.unlp.edu.ar/public/images/payments/' + p.voucher_image  }}" alt="comprobante">
                <button onclick="hideVoucher('{{p.orden}}')">Cerrar</button>
            </div>
            <button id="{{p.orden}}" onclick="showVoucher('{{p.orden}}')">Ver Comprobante</button>
            <form action="{{ url_for('payments.aprobar_pago',current_page=return_page,pagoId=p.id) }}" method="POST">
                <button type="submit">Aprobar pago</button>
            </form>
            <form action="{{ url_for('payments.rechazar_pago',current_page=return_page,pagoId=p.id) }}" method="POST">
                <button type="submit">Rechazar pago</button>
            </form>
        </li>
        {% endfor %}
    </ul>
{% endif %}
{% if empty %}
    <h1 style="margin-left: 20px;margin-bottom: 20px;color: white;">No hay pagos pendientes</h1>
{% endif %}

<a class="btn-nuevo-pago" style="margin-left: 20px;"
    href="{{ url_for('payments.payment_index_page', num=return_page) }}">Volver</a>

<script>
    function showVoucher(id){
        const image = document.getElementById(`image${id}`)
        image.style.display = "block"
    }
    function hideVoucher(id){
        const image = document.getElementById(`image${id}`)
        image.style.display = "none"
    }
</script>

{% endblock %}