admin/src/web/controllers/perfil.py
import os

from flask import Blueprint, render_template, redirect, url_for, flash
from flask import session, request, current_app
from werkzeug.utils import secure_filename


from src.web.helpers.auth import token_required, decode_token
from src.core import auth

perfil_blueprint = Blueprint("perfil", __name__, url_prefix="/perfil")


@perfil_blueprint.get("/")
@token_required
def perfil():
    userToken = decode_token(session["user"])
    if userToken is None:
        return redirect(url_for("auth.logout"))
    user = auth.find_user_by_mail(userToken["user"]).items[0]
    return render_template(
        "user/perfil.html", user=user, editDescription=False, editImg=False
    )


@perfil_blueprint.route("/description", methods=("GET", "POST"))
@token_required
def edit_description():
    userToken = decode_token(session["user"])
    if userToken is None:
        return redirect(url_for("auth.logout"))
    user = auth.find_user_by_mail(userToken["user"]).items[0]
    if request.method == "POST":
        params = request.form
        if params["texDes"]:
            user = auth.edit_description_user(user, params["texDes"].strip())
            flash("Descripción actualizada", "success")
            return render_template(
                "user/perfil.html", user=user, editDescription=False, editImg=False
            )
        else:
            flash("No se envió ninguna descripción", "error")
    return render_template(
        "user/perfil.html", user=user, editDescription=True, editImg=False
    )


ALLOWED_EXTENSIONS = set([".png", ".jpg", ".jpeg"])


@perfil_blueprint.route("/photo/change", methods=("GET", "POST"))
@token_required
def change_photo():
    userToken = decode_token(session["user"])
    if userToken is None:
        return redirect(url_for("auth.logout"))
    user = auth.find_user_by_mail(userToken["user"]).items[0]
    if request.method == "POST":
        file = request.files["archivo"]
        filename = secure_filename(file.filename)  # Nombre original del archivo

        # capturando extensión del archivo ejemplo: (.png, .jpg, .pdf ...etc)
        extension = os.path.splitext(filename)[1]

        # verifico el tipo de archivo
        if not extension in ALLOWED_EXTENSIONS:
            flash("Tipo de archivo no valido.", "error")
            return redirect(url_for("perfil.perfil"))

        newNameFile = auth.save_photo_user(extension, file, user.email)

        if newNameFile is None:
            flash("Fallo al guardar la foto.", "error")
            return redirect(url_for("perfil.perfil"))

        session["photo"] = newNameFile

        flash("Foto actualizada.", "success")
        return redirect(url_for("perfil.perfil"))
    return render_template(
        "user/perfil.html", user=user, editDescription=False, editImg=True
    )

admin/src/web/controllers/users.py
from flask import Blueprint, render_template, request
from flask import flash, redirect, url_for
from flask import session


from src.core import auth
from src.core import associates
from src.core import setting
from src.web.helpers.auth import token_required, user_has_permission, decode_token
from src.web.helpers import validate

user_blueprint = Blueprint("users", __name__, url_prefix="/usuarios")


@user_blueprint.get("/<int:num>")
@token_required
@user_has_permission("users_index")
def user_index(num):
    users = auth.list_Users_paginate(num, setting.get_setting().cant_elements_page)
    return render_template("user/users.html", users=users, filterState=False)


@user_blueprint.post("/filtrar")
@token_required
@user_has_permission("users_index")
def filtrar():
    """Filtra la lista de usuario por email y/o estado"""
    params = request.form
    if params["email"] != "":
        user = auth.find_user_by_mail(params["email"])
        if not user.items:
            flash(f"El email: {params['email']} no existe", "error")
            return redirect(url_for("users.user_index", num=1))
        return render_template("user/users.html", users=user)
    if params["estado"] != "all":
        return redirect(
            url_for("users.paginaFiltroEstado", state=params["estado"], num=1)
        )
    return redirect(url_for("users.user_index", num=1))


def corroborarEstado(estate):
    if estate == "bloqueado":
        return False
    return True


@user_blueprint.get("/filtrar_estado/<state>/<int:num>")
@token_required
@user_has_permission("users_index")
def paginaFiltroEstado(state, num):
    """Filtra la lista de usuario segun el estado"""
    # falta traer de configuración la cantidad de elementos a mostrar
    estado = corroborarEstado(state)
    users = auth.find_user_by_active(
        estado, num, setting.get_setting().cant_elements_page
    )
    if not users.items:
        flash(f"Sin resultados", "info")
    return render_template(
        "user/users.html", users=users, filterState=True, state=state
    )


@user_blueprint.get("/detalle/<int:user_id>/<int:current_page>")
@token_required
@user_has_permission("users_show")
def user_detail(user_id, current_page):
    """muestra la ventana con los datos del usuario"""
    user = auth.find_user_by_id(user_id)
    return render_template("user/user_detail.html", user=user, return_page=current_page)


@user_blueprint.get("/nuevo_usuario/<int:current_page>")
@token_required
@user_has_permission("users_new")
def new_user(current_page):
    """muestra la ventana del formulario para agregar un usuario"""
    return render_template("user/new_user.html", params=None, return_page=current_page)


@user_blueprint.route(
    "/modificar_usuario/<int:user_id>/<int:current_page>", methods=("GET", "POST")
)
@token_required
@user_has_permission("users_update")
def update_user(user_id, current_page):
    """muestra la ventana del formulario para modificar un usuario"""
    user = auth.find_user_by_id(user_id)
    if request.method == "POST":
        params = request.form
        if not validate.userName(params["userName"]):
            flash(
                "El nombre de Usuario solo puede contener numeros, letras y guion bajo",
                "error",
            )
            return render_template(
                "user/user_update.html", user=user, current_page=current_page
            )
        if not validate.name(params["first_name"]):
            flash("Nombre no valido", "error")
            return render_template(
                "user/user_update.html", user=user, current_page=current_page
            )
        if not validate.name(params["last_name"]):
            flash("Apellido no valido", "error")
            return render_template(
                "user/user_update.html", user=user, current_page=current_page
            )
        if params["password"] != "":
            result = validate.validatePassword(params["password"])
            if not result["user"]:
                flash(result["message"], "error")
                return render_template(
                    "user/new_user.html", params=params, return_page=current_page
                )
        result = auth.verify_update_user(params, user)
        if not result["user"]:
            flash(result["message"], "error")
            return render_template(
                "user/user_update.html", user=user, current_page=current_page
            )
        flash(result["message"], "success")
        return redirect(
            url_for("users.user_detail", user_id=user.id, current_page=current_page)
        )
    return render_template(
        "user/user_update.html", user=user, current_page=current_page
    )


@user_blueprint.post("/nuevo_usuario/<int:current_page>")
@token_required
@user_has_permission("users_new")
def add_user(current_page):
    """verifica los datos del nuevo usuario y lo agrega"""
    params = request.form
    if not validate.email(params["email"]):
        flash("Correo no válido", "error")
        return render_template(
            "user/new_user.html", params=params, return_page=current_page
        )

    if not validate.userName(params["userName"]):
        flash(
            "El nombre de Usuario solo puede contener numeros, letras y guion bajo",
            "error",
        )
        return render_template(
            "user/new_user.html", params=params, return_page=current_page
        )

    if not validate.name(params["first_name"]):
        flash("Nombre no valido", "error")
        return render_template(
            "user/new_user.html", params=params, return_page=current_page
        )

    if not validate.name(params["last_name"]):
        flash("Apellido no valido", "error")
        return render_template(
            "user/new_user.html", params=params, return_page=current_page
        )
    result = validate.validatePassword(params["password"])
    if not result["user"]:
        flash(result["message"], "error")
        return render_template(
            "user/new_user.html", params=params, return_page=current_page
        )

    result = auth.verify_new_user(params)

    if not result["user"]:
        flash(result["message"], "error")
        return render_template(
            "user/new_user.html", params=params, return_page=current_page
        )
    flash(result["message"], "success")
    return redirect(
        url_for(
            "users.user_detail",
            user_id=result["user"].id,
            current_page=current_page,
        )
    )


@user_blueprint.get("/alternar_activo/<int:user_id>/<int:pag_actual>")
@token_required
@user_has_permission("users_update")
def toggle_blocked(user_id, pag_actual):
    """Alterna el bloqueo a un usuario no administrador"""
    result = auth.block_user(user_id)
    if not result["user"]:
        flash(result["message"], "error")
        return redirect(url_for("users.user_index", num=pag_actual))
    flash(result["message"], "success")
    return redirect(url_for("users.user_index", num=pag_actual))


@user_blueprint.post("/roles/<int:user_id>/<int:current_page>")
@token_required
@user_has_permission("users_update")
def asig_role(user_id, current_page):
    """muestra la ventana con los datos del usuario"""
    user = auth.find_user_by_id(user_id)
    params = request.form
    roles = auth.list_Roles()
    email_logged_in = decode_token(session["user"])["user"]
    asigSocio = False
    for role in roles:
        if role.name in params:
            if role.name == "socio" and not role in user.role:
                asigSocio = True
            else:
                auth.assign_role(user, role)
        elif role.name == "administrador" and user.email == email_logged_in:
            flash("No puedes quitarte el rol administrador a vos mismo", "error")
            return render_template(
                "user/user_detail.html", user=user, return_page=current_page
            )
        elif role.name == "socio" and user.associated:
            flash(
                "No puedes quitarle el rol socio, el usuario tiene asociados vinculados",
                "error",
            )
            return render_template(
                "user/user_detail.html", user=user, return_page=current_page
            )
        elif role in user.role:
            auth.remove_user_role(user, role)
    if asigSocio:
        return redirect(
            url_for(
                "users.listAssociates",
                user_id=user_id,
                num=1,
                current_page=current_page,
            )
        )
    flash("Roles actualizados", "success")
    return render_template("user/user_detail.html", user=user, return_page=current_page)


@user_blueprint.get("/eliminar/<int:user_id>/<int:current_page>")
@token_required
@user_has_permission("users_destroy")
def delete_user_by_id(user_id, current_page):
    """Recibe una id de disciplina y la elimina de la BD."""
    result = auth.delete_by_id(user_id)
    if not result["user"]:
        flash(result["message"], "error")
        return redirect(url_for("users.user_index", num=current_page))
    flash(result["message"], "success")
    return redirect(url_for("users.user_index", num=current_page))


@user_blueprint.get("/<int:user_id>/associados/pagina/<int:num>")
@token_required
@user_has_permission("users_update")
def listAssociates(user_id, num):
    """Muestra la lista de asociados disponibles para asignar al usuario socio"""
    listAssociates = associates.list_associates_no_user(
        num, setting.get_setting().cant_elements_page
    )
    return render_template(
        "user/asig_associated.html",
        user_id=user_id,
        associates=listAssociates,
    )


@user_blueprint.get(
    "/<int:user_id>/asignar_asociado/<int:associated_id>/<int:current_page>"
)
@token_required
@user_has_permission("users_update")
def asig_associate(user_id, associated_id, current_page):
    """verifica que un asociado puede agregar la relacion con el socio"""

admin/src/web/templates/user/asig_associated.html
{% extends 'layout.html' %}
{% set active_page = "users" %}
{% block css %}
<link rel="stylesheet" href="{{ url_for('static',filename='css/associates/associates.css') }}">
{% endblock %}
{% block liks %}
<script src="https://kit.fontawesome.com/e480f6dd1b.js" crossorigin="anonymous"></script>
{% endblock%}
{% block title %}
<title>Asociados</title>
{% endblock %}

{% block content %}

<table id="tableAsociated" class="tabla">
    <caption>
        <div class="div-titulo-buscar">
            <h1 class="nom-pagina">Listado de asociados:</h1>
        </div>
    </caption>
    <thead>
        <tr>
            <th># socio</th>
            <th>Nombre</th>
            <th>Apellido</th>
            <th># documento</th>
            <th>Tipo</th>
            <th>Asignar</th>
        </tr>
    </thead>
    <tbody>
        {% if associates.items %}
        {% for associated in associates.items %}
        <tr>
            <td>{{ associated.id }}</td>
            <td>{{ associated.name }}</td>
            <td>{{ associated.surname }}</td>
            <td>{{ associated.document_number }}</td>
            <td>{{ associated.document_type }}</td>
            <td>
                <a class="btn btn-detalle"
                    href="{{ url_for('users.asig_associate', user_id=user_id, associated_id=associated.id, current_page=associates.page)}}">Asignar</a>
            </td>
        </tr>
        {% endfor %}
        {% else %}
        <td></td>
        <td></td>
        <td>Sin Asociados</td>
        <td></td>
        <td></td>
        <td></td>
        {% endif %}
    </tbody>
</table>

<div class="paginacion">
    <ul>
        {% for page_num in associates.iter_pages(left_edge=1, left_current=3, right_current=3, right_edge=1) %}

        {% if page_num %}
        {% if page_num==associates.page %}
        <li>
            <a class="active">{{ page_num }}</a>
        </li>
        {% else %}
        <li>
            <a href="{{ url_for('users.listAssociates', user_id=user_id, num=page_num) }}">{{ page_num }}</a>
        </li>
        {% endif %}
        {% else %}
        <li>
            <a class="threePoints">...</a>
        </li>
        {% endif %}
        {% endfor %}

    </ul>
</div>
{% endblock %}

admin/src/web/templates/user/new_user.html
{% extends 'layout.html' %}
{% set active_page = "users" %}
{% block css %}
<link rel="stylesheet" href="{{ url_for('static',filename='css/users/new_user.css') }}">
{% endblock %}
{% block title %}
<title>Nuevo usuario</title>
{% endblock %}

{% block nav %}
{{super()}}
{% endblock %}
{% block content %}

<div class="div-form">
    <h2>Nuevo Usuario</h2>
    <form id="for-box" action="{{ url_for('users.add_user', current_page=return_page)}}" method="post">
        <label class="labelCorreo">Correo:</label>
        <input class="inputCorreo" type="email" id="email" name="email" maxlength="50" placeholder="Ingrese el email" {%
            if params %} value="{{ params['email'].lower().strip()  }}" {% endif %} autocomplete="off" required>
        <label class="labelUserName">Nombre de usuario:</label>
        <input class="inputUserName" type="text" id="userName" name="userName" maxlength="50"
            placeholder="Ingrese el nombre de usuario" {% if params %} value="{{ params['userName'].strip()  }}" {%
            endif %} autocomplete="off" required>
        <label class="labelPass">Contraseña:</label>
        <input class="inputPass" type="password" id="new-user-pass" name="password" placeholder="Ingrese una contraseña"
            maxlength="30" {% if params %} value="{{ params['password']  }}" {% endif %} required>
        <label class="labelApellido">Apellido:</label>
        <input class="inputApellido" type="text" id="new-user-last-name" name="last_name" maxlength="100"
            placeholder="Ingrese el apellido" {% if params %} value="{{ params['last_name'].strip()  }}" {% endif %}
            required>
        <label class="labelNombre">Nombre:</label>
        <input class="inputNombre" type="text" id="new-user-first-name" name="first_name" maxlength="100"
            placeholder="Ingrese el nombre" {% if params %} value="{{ params['first_name'].strip()  }}" {% endif %}
            required>
        <input class="botonAgregar" type="submit" value="Agregar Usuario">
        <a class="botonCancelar" href="{{ url_for('users.user_index', num=return_page) }}">cancelar</a>
    </form>
</div>
{% endblock %}

admin/src/web/templates/user/perfil.html
{% extends 'layout.html' %}
{% set active_page = "perfil" %}
{% block css %}
<link rel="stylesheet" href="{{ url_for('static',filename='css/perfil.css') }}">
{% endblock %}
{% block liks %}
<script src="https://kit.fontawesome.com/e480f6dd1b.js" crossorigin="anonymous"></script>
{% endblock %}
{% block title %}
<title>Perfil</title>
{% endblock %}

{% block nav %}
{{super()}}
{% endblock %}
{% block content %}
<div class="contenedor_perfil">
    <h1 class="nom-pagina">Perfil</h1>
    <div class="contenedor_acerca_de_mi">
        <h4 class="titulo_acerca_mi">Acerca de mí {% if editDescription == False %}<a id="btn-edit"
                title="Editar descripción usuario" href="{{ url_for('perfil.edit_description') }}"><i
                    class="fa-solid fa-pen-to-square"></i></a> {% endif %}</h4>
        {% if editDescription %}
        <form class="form-des" action="{{url_for('perfil.edit_description')}}" method="post">
            <!-- <input placeholder="Cuéntanos sobre ti" type="text" name="archivo" required> -->
            <textarea name="texDes" rows="10" cols="50" required
                placeholder="Cuéntanos sobre ti">{% if user.description != '-' %}{{ user.description }}{% endif%}</textarea><br>
            <input type="submit" value="Actualizar"></input>
        </form>
        <a class="btn-volver" title="cancelar" href="{{ url_for('perfil.perfil') }}">Cancelar</a>
        {% else %}
        <p class="parrafo_acerca_mi">{{ user.description }}</p>
        {% endif %}
    </div>
    <div class="contenedor_img_user">
        <div style="text-align: center;">
            <img class="img_user"
                src="{{ 'https://admin-grupo17.proyecto2022.linti.unlp.edu.ar/public/images/users/' + user.photo }}"
                alt="foto de usuario" data-image-width="700" data-image-height="700">
            <h4>Cambiar foto de perfil {% if editImg == False %}<a id="btn-edit" title="Actualizar foto de perfil"
                    href="{{ url_for('perfil.change_photo') }}"><i class="fa-solid fa-pen-to-square"></i></a> {% endif
                %}
            </h4>
            {% if editImg %}
            <form class="form-img" action="{{ url_for('perfil.change_photo') }}" method="post" autocomplete="off"
                enctype="multipart/form-data">
                <input title="file" placeholder="subir una foto" type="file" name="archivo" required
                    accept=".png, .jpg, .jpeg">
                <input type="submit"></input>
            </form>
            <a class="btn-volver" title="cancelar" href="{{ url_for('perfil.perfil') }}">Cancelar</a>
            {% endif %}
        </div>
    </div>
    <div class="contenedor_detalles">
        <p class="parrafo_detalles">
            <span style="font-weight: 700;">Nombre: </span>
            <br>{{ user.first_name }} {{ user.last_name}}<br>
            <span style="font-weight: 700;">Nombre de Usuario: </span>
            <br>{{ user.userName }}<br>
            <span style="font-weight: 700;">Email: </span>
            <br>{{ user.email }}<br>
            <span style="font-weight: 700;">
                <br>Location:
            </span>
            <br>La Plata - Buenos Aires - Argentina
        </p>
    </div>
</div>
{% endblock %}

admin/src/web/templates/user/user_detail.html
{% extends 'layout.html' %}
{% set active_page = "users" %}
{% block css %}
<link rel="stylesheet" href="{{ url_for('static',filename='css/users/user_detail.css') }}">
{% endblock %}
{% block liks %}
<script src="https://kit.fontawesome.com/e480f6dd1b.js" crossorigin="anonymous"></script>
{% endblock %}
{% block title %}
<title>Detalle usuario</title>
{% endblock %}

{% block nav %}
{{super()}}
{% endblock %}
{% block content %}


<div id="for-box">
    <div class="cabecera h2DatosPersonales"><i class="fa-solid fa-database"></i>
        <h2>Datos personales:</h2>
    </div>
    <div class="datoEmail">
        <label class="labelEmail">Email: </label>
        <label class="dato">{{user.email}}</label>
    </div>
    <div class="datoNombre">
        <label class="labelNombre">Nombre: </label>
        <label class="dato">{{user.first_name}}</label>
    </div>
    <div class="datoApellido">
        <label class="labelApellido">Apellido: </label>
        <label class="dato">{{user.last_name}}</label>
    </div>

    <div class="cabecera h2DatosCuenta"><i class="fa-solid fa-user-large"></i>
        <h2>Datos de la cuenta:</h2>
    </div>
    <div class="datoUserName">
        <label class="labelUsuario">Usuario: </label>
        <label class="dato">{{user.userName}}</label>
    </div>
    <div class="datoEstado">
        <label class="labelEstado">estado: </label>
        <label class="dato">{% if user.active %}activo {% else %} bloqueado {% endif %}</label>
    </div>

    <div class="cabecera h2DatosRoles"><i class="fa-solid fa-screwdriver-wrench"></i>
        <h3>Roles:</h3>
    </div>
    <div class="d6" id="form-roles" style="display: none;">
        <form class="formAsigRole" action="{{ url_for('users.asig_role', user_id=user.id, current_page=return_page)}}"
            method="POST">
            <div>
                <input type="checkbox" id="checkboxAdmin" {% if user_is_role(user, 'administrador' )%} checked="" {%
                    endif %} name="administrador" value="administrador" />
                <label class="dato">Administrador</label>
            </div>
            <div>
                <input type="checkbox" id="checkboxOperador" {% if user_is_role(user, 'operador' )%} checked="" {% endif
                    %} name="operador" value="operador" />
                <label class="dato">Operador</label>
            </div>
            <div>
                <input type="checkbox" id="checkboxSocio" {% if user_is_role(user, 'socio' )%} checked="" {% endif %}
                    name="socio" value="socio" />
                <label class="dato">Socio</label>
            </div>
            <input type="submit" value="actualizar roles">
        </form>
    </div>
    <div id="roles-user" class="d6" style="display: block;">
        {% if not user.role %}
        <label class="dato sinRoles">sin asignar</label>
        {% else %}
        {% for rol in user.role %}
        <label class="dato">{{ rol.name }}</label>
        {% endfor %}
        {% endif %}
    </div>
    {% if user_is_role(user, 'socio' ) %}
    <div class="cabecera h2DatosAsociados"><i class="fa-solid fa-users"></i>
        <h3>Asociado:</h3>
    </div>
    <div class="datoAsociados">
        {% if not user.associated %}
        <label class="dato ">Sin asociados</label>
        {% else %}
        <label class="dato d7">#Socio:
            {{user.associated[0].id}} | {{user.associated[0].document_type}}:
            {{user.associated[0].document_number}} | Nombre: {{user.associated[0].surname}}
            {{user.associated[0].name}}</label>
        {% endif %}
    </div>
    <div class="div-btn-asociado">
        {% if user.associated %}
        <a href="{{ url_for('users.remove_associate', user_id=user.id, current_page=return_page)}}"
            class="btn btn-delete" id="btn-delete-asociado">eliminar</a>
        {% endif %}
    </div>


    {% endif %}
    <div class="linea"></div>
    <div id="div-botones">
        <a class="btn btn-modificar"
            href="{{ url_for('users.update_user', user_id=user.id, current_page=return_page) }}">modificar</a>
        <a class="btn btn-volver" href="{{ url_for('users.user_index', num=return_page) }}">volver</a>
        <a class="btn btn-roles" id="btn-roles">asignar rol</a>
    </div>

</div>

{% endblock %}
{% block script %}
<script>
    let showAsigRole = false

    const btnAsigRole = document.getElementById("btn-roles");
    const rolesUser = document.getElementById("roles-user");
    const formRoles = document.getElementById("form-roles");

    btnAsigRole.addEventListener('click', () => {
        if (showAsigRole) {
            rolesUser.style.display = "block";
            formRoles.style.display = "none";
            btnAsigRole.innerText = "asignar rol"
        } else {
            rolesUser.style.display = "none";
            formRoles.style.display = "block";
            btnAsigRole.innerText = "cancelar"
        }
        showAsigRole = !showAsigRole;
    });

</script>
{% endblock %}

admin/src/web/templates/user/users.html
{% extends 'layout.html' %}
{% set active_page = "users" %}
{% block css %}
<link rel="stylesheet" href="{{ url_for('static',filename='css/users/users.css') }}">
{% endblock %}
{% block liks %}
<script src="https://kit.fontawesome.com/e480f6dd1b.js" crossorigin="anonymous"></script>
{% endblock %}
{% block title %}
<title>Usuarios</title>
{% endblock %}

{% block nav %}
{{super()}}
{% endblock %}
{% block content %}



<table class="tabla">
    <caption>
        <div class="div-titulo-buscar">
            <h1 class="nom-pagina">Lista de usuarios:</h1>
            <div class="div-buscar">
                <form class="buscar" action="{{ url_for('users.filtrar')}}" method="POST">
                    <select class="select-estado" name="estado">
                        <option value="all">Estado</option>
                        <option value="activo">activos</option>
                        <option value="bloqueado">bloqueados</option>
                    </select>
                    <input type="email" class="buscar_email" name="email" placeholder="Ingrese el email"
                        autocomplete="off">
                    <button title="filtrar" class="boton-filtrar" type="submit"><i
                            class="fa-solid fa-magnifying-glass"></i></button>
                </form>
            </div>
        </div>

    </caption>
    <thead>
        <tr>
            <th class="user-email">Email</th>
            <th class="user-username">Usuario</th>
            <th>Apellido</th>
            <th>Nombre</th>
            <th class="user-estate">Estado</th>
            <th>Detalle</th>
            <th>Bloquear</th>
            <th>Eliminar</th>
        </tr>
    </thead>
    <tbody>
        {% if users.items %}
        {% for user in users.items %}
        <tr>
            <td class="user-email">{{ user.email }}</td>
            <td class="user-username">{{ user.userName }}</td>
            <td>{{ user.last_name }}</td>
            <td>{{ user.first_name }}</td>
            {% if user.active==True %}
            <td class="user-estate">Activo</td>
            {% else %}
            <td class="user-estate">Bloqueado</td>
            {% endif %}
            <td><a class="btn btn-detalle"
                    href="{{ url_for('users.user_detail', user_id=user.id, current_page=users.page) }}">Detalle</a>
            </td>
            <td>{% if user.active==True %}<a class="btn btn-bloquear"
                    href="{{ url_for('users.toggle_blocked', user_id=user.id, pag_actual=users.page) }}"> Bloquear </a>
                {% else %} <a class="btn btn-desbloquear"
                    href="{{ url_for('users.toggle_blocked', user_id=user.id, pag_actual=users.page) }}">Desbloquear</a>
                {% endif %}
            </td>
            <td><a class="btn btn-eliminar"
                    href="{{ url_for('users.delete_user_by_id', user_id=user.id, current_page=users.page) }}"
                    onclick="return confirm('¿Quiere eliminar a {{user.email}}?')">Eliminar</a>
            </td>

        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>No hay Usuarios</td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        {% endif %}
    </tbody>
</table>
<div class="paginacion">
    <ul>
        {% for page_num in users.iter_pages(left_edge=1, left_current=3, right_current=3, right_edge=1) %}

        {% if page_num %}
        {% if page_num==users.page %}
        <li>
            <a class="active">{{ page_num }}</a>
        </li>
        {% else %}
        <li>
            <a {% if filterState %} href="{{ url_for('users.paginaFiltroEstado',state=state, num=page_num) }}" {% else
                %} href="{{ url_for('users.user_index', num=page_num) }}" {% endif %}>{{ page_num }}</a>
        </li>
        {% endif %}
        {% else %}
        <li>
            <a class="threePoints">...</a>
        </li>
        {% endif %}
        {% endfor %}

    </ul>
</div>
<div class="div-btn">
    <a id="boton-agregar-usuario" href="{{ url_for('users.new_user', current_page=users.page) }}">Agregar usuario</a>
</div>

{% endblock %}