admin/src/web/controllers/associates.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, current_app
from src.core import sports
from src.core import setting
from src.core import associates
from src.core import payments
from src.core import licenses
from src.web.helpers.auth import token_required, user_has_permission, token_required
from werkzeug.utils import secure_filename
import os
import qrcode
from PIL import Image
from random import sample
import shutil

associated_blueprint = Blueprint("associates", __name__, url_prefix="/asociados")


@associated_blueprint.post("/new/<int:current_page>")
@token_required
@user_has_permission("associates_new")
def add_associated(current_page):
    """Recibe datos y crea un nuevo asociado. Luego Redirecciona."""
    params = request.form
    result = associates.verify_new_associated(params)
    if not result["associated"]:
        flash(result["message"], "error")
        return render_template(
            "associates/new_associated.html", return_page=current_page
        )
    flash(result["message"], "success")
    return redirect(url_for("associates.associated_index_page", num=current_page))


@associated_blueprint.get("/<int:num>")
@token_required
@user_has_permission("associates_index")
def associated_index_page(num):
    """Trae asociados paginadas."""
    associated = associates.list_associates_page(
        num, setting.get_setting().cant_elements_page
    )
    return render_template(
        "associates/associates.html",
        associates=associated,
        filterState=[False, "", "", ""],
    )


@associated_blueprint.get("/detalle/<int:associated_id>/<int:current_page>")
@token_required
@user_has_permission("associates_index")
def associated_detail(associated_id, current_page):
    """Muestra la ventana con los datos del asociado"""
    associated = associates.get_associated_by_id(associated_id)
    return render_template(
        "associates/associated_detail.html",
        associated=associated,
        current_page=current_page,
    )


def corroborarEstado(estate):
    if estate == "bloqueado":
        return "No-activo"
    return "Activo"


ALLOWED_EXTENSIONS = set([".png", ".jpg", ".jpeg"])

def stringRandom():
    """Genera un string aleatorio"""
    string_random = "0123456789abcdefghijkmnopqrstuvwxyz_"
    long = 20
    sequence = string_random.upper()
    result_random = sample(sequence, long)
    string_random = "".join(result_random)
    return string_random


def save_photo_associated(extension, file):
    """Crea un nuevo nombre y guarda la foto en la ruta por defecto"""
    # asigno un nombre nuevo random, para evitar coincidencias
    newNameFile = stringRandom() + extension

    # establezco la ruta para guardar y lo guardo
    upload_path = os.path.join(current_app.config["UPLOAD_FOLDER"], "images/users", newNameFile)
    file.save(upload_path)
    file.close()

    # actualizo la foto del usuario
    return newNameFile

    
def save_qr_associated(associated_id):
    """Genera codigo qr"""
    cadena = f"https://admin-grupo17.proyecto2022.linti.unlp.edu.ar/asociados/carnet/detalles/{associated_id}/1"
    imagen = qrcode.make(cadena)

    nombre_imagen = stringRandom() + ".png"
    archivo_imagen = open(nombre_imagen, 'wb')
    imagen.save(archivo_imagen)
    archivo_imagen.close()
    
    origen = os.path.join("./", nombre_imagen)
    destino = os.path.join(current_app.config["UPLOAD_FOLDER"], "images/qr")
    
    shutil.move(origen,destino)

    return nombre_imagen

@associated_blueprint.post("/carnet/generar/<associated_id>/<int:current_page>")
@token_required
@user_has_permission("carnet_new")
def create_credential(associated_id, current_page):
    """Crea un carnet para un asociado con una imagen, qr y sus datos personales en la BD."""
    file = request.files["archivo"]
    if file:
        filename = secure_filename(file.filename)
        extension = os.path.splitext(filename)[1]
        if not extension in ALLOWED_EXTENSIONS:
            flash("Tipo de archivo no valido.", "error")
            return redirect(url_for("associates.new_credential_form", associated_id = associated_id, current_page = current_page))
        newNameFile = save_photo_associated(extension, file)
    else:
        newNameFile = "sin-usuario.png"

    "Genera codigo qr"
    name_qr = save_qr_associated(associated_id)

    "Crea licencia"
    licenses.create_license(
        associated_id = associated_id,
        photo = newNameFile,
        qr = name_qr,
    )
    
    "Retorna a asociados"
    return redirect(url_for("associates.associated_index_page", num=current_page))


def create_credential_automatic(associated_id):
    "Obtengo la foto de perfil del usuario"
    name_photo = associates.get_associated_by_id(associated_id).user.photo
 
    "Genera codigo qr"
    name_qr = save_qr_associated(associated_id)

    "Crea licencia"
    licenses.create_license(
        associated_id = associated_id,
        photo = name_photo,
        qr = name_qr,
    )


@associated_blueprint.get("/delete/<associated_id>/<int:current_page>")
@token_required
@user_has_permission("associates_destroy")
def delete_associated_by_id(associated_id, current_page):
    """Recibe una id de un asociado y lo elimina de la base de datos validandolo."""
    associated_to_delete = associates.get_associated_by_id(associated_id)
    tiene_pagos = payments.find_payment_by_id_associated(associated_to_delete.id)
    if tiene_pagos and associated_to_delete.sports:
        flash(
            f"El asociado: {associated_id} no se puede eliminar porque tiene pagos y esta anotado en disciplinas.",
            "error",
        )
        return redirect(url_for("associates.associated_index_page", num=current_page))
    if tiene_pagos:
        flash(
            f"El asociado: {associated_id} no se puede eliminar porque tiene pagos.",
            "error",
        )
        return redirect(url_for("associates.associated_index_page", num=current_page))
    if associated_to_delete.sports:
        flash(
            f"El asociado: {associated_id} no se puede eliminar porque esta anotado en disciplinas",
            "error",
        )
        return redirect(url_for("associates.associated_index_page", num=current_page))
    associates.delete_associated(associated_to_delete)
    return redirect(url_for("associates.associated_index_page", num=1))


@associated_blueprint.post("/filtrar")
@token_required
@user_has_permission("associates_index")
def filtrar():
    """Filtra la lista de asociados por estado y/o apellido."""
    params = request.form
    if params["estado"] != "all" and params["surname"] != "":
        return redirect(
            url_for(
                "associates.filtrarApellidoEstado",
                estado=params["estado"],
                surname=params["surname"],
                num=1,
            )
        )
    if params["surname"] != "":
        return redirect(
            url_for("associates.filtrarApellido", surname=params["surname"], num=1)
        )
    if params["estado"] != "all":
        return redirect(
            url_for("associates.filtrarEstado", estado=params["estado"], num=1)
        )
    return redirect(url_for("associates.associated_index_page", num=1))


@associated_blueprint.get("/filtrar_apellido/<surname>/<int:num>")
@token_required
@user_has_permission("associates_index")
def filtrarApellido(surname, num):
    """Filtra la lista de asociados segun el apellido."""
    associated = associates.find_associated_by_surname(
        surname, setting.get_setting().cant_elements_page, num
    )
    if not associated.items:
        flash(f"El asociado: {surname} no existe", "error")
        return redirect(url_for("associates.associated_index_page", num=1))
    return render_template(
        "associates/associates.html",
        associates=associated,
        filterState=[True, "apellido", surname, ""],
    )


@associated_blueprint.get("/filtrar_apellido_estado/<surname>/<estado>/<int:num>")
@token_required
@user_has_permission("associates_index")
def filtrarApellidoEstado(estado, surname, num):
    """Filtra la lista de asociados segun el apellido y estado."""
    condition = corroborarEstado(estado)
    associated = associates.find_associated_by_surname_and_condition(
        surname, condition, setting.get_setting().cant_elements_page, num
    )
    if not associated.items:
        flash(
            f"El asociado: {surname} no existe o no se encuentra {condition}", "error"
        )
        return redirect(url_for("associates.associated_index_page", num=1))
    return render_template(
        "associates/associates.html",
        associates=associated,
        filterState=[True, "apellido_y_estado", surname, estado],
    )


@associated_blueprint.get("/filtrar_estado/<estado>/<int:num>")
@token_required
@user_has_permission("associates_index")
def filtrarEstado(estado, num):
    """Filtra la lista de asociados segun el estado."""
    condition = corroborarEstado(estado)
    associated = associates.find_associated_by_active(
        condition, num, setting.get_setting().cant_elements_page
    )
    if not associated.items:
        flash(f"No se encontraron asociados {estado}s", "info")
        return redirect(url_for("associates.associated_index_page", num=1))
    return render_template(
        "associates/associates.html",
        associates=associated,
        filterState=[True, "estado", "", estado],
    )


@associated_blueprint.get("/new/<int:current_page>")
@token_required
@user_has_permission("associates_new")
def new_associated_form(current_page):
    """Muestra formulario para agregar un asociado."""
    return render_template(
        "associates/new_associated.html", nav_menu=False, return_page=current_page
    )


@associated_blueprint.get("/carnet/detalles/<int:associated_id>/<int:current_page>")
@token_required
@user_has_permission("carnet_view")
def associated_license(associated_id, current_page):

admin/src/web/controllers/signups.py
from flask import Blueprint, render_template, redirect, url_for, abort, flash

from src.core import setting
from src.core import sports
from src.core import associates
from src.core import setting
from src.web.helpers.auth import token_required, user_has_permission

signup_blueprint = Blueprint("signups", __name__, url_prefix="/inscripciones")


# Fuera de uso
# @signup_blueprint.get("/<int:sport_id>/<int:current_page>")
# @token_required
# @user_has_permission("signup_list")
# def signups_list(sport_id, current_page):
#     """Trae todos los inscriptos a una disciplina."""
#     sport_ret = sports.get_sport_by_id(sport_id)
#     return render_template(
#         "sports/signedup.html",
#         associates=sport_ret.associates,
#         sport_id=sport_id,
#         return_page=current_page,
#     )


@signup_blueprint.get("/<int:sport_id>/<int:return_page>/<int:associates_page>")
@token_required
@user_has_permission("signup_list")
def signups_list_page(sport_id, return_page, associates_page):
    """Trae los inscriptos a una disciplina paginados."""
    sport_ret = sports.get_sport_by_id(sport_id)
    associates_ret = associates.get_signed_associated(
        sport_ret, associates_page, setting.get_setting().cant_elements_page
    )
    return render_template(
        "sports/signedup.html",
        associates=associates_ret,
        sport_id=sport_id,
        return_page=return_page,
        associates_page=associates_page,
    )


@signup_blueprint.get(
    "/<int:sport_id>/<int:associate_id>/<int:return_page>/<int:associates_page>/<int:sign_page>"
)
@token_required
@user_has_permission("signup_new")
def sign_associate(sport_id, associate_id, return_page, associates_page, sign_page):
    """Inscribe un asociado a una discplina."""
    sport_ret = sports.get_sport_by_id(sport_id)
    sign = True
    if sport_ret.enabled is False:
        abort(404)

    associate_ret = associates.get_associated_by_id(associate_id)
    if associate_ret.condition == "No-activo":
        flash("El associado no esta activo.", "error")
        sign = False

    if associates.is_defaulter(associate_id):
        flash("El associado es moroso.", "error")
        sign = False

    if sport_ret in associate_ret.sports:
        flash("El associado ya se encuentra inscripto.", "error")
        sign = False

    if sign:
        sports.append_to_associates(sport_ret, associate_ret)
        flash("Inscripcion ralizada", "success")

    return redirect(
        url_for(
            "signups.sign_associate_form",
            sport_id=sport_id,
            return_page=return_page,
            associates_page=associates_page,
            sign_page=sign_page,
        )
    )


@signup_blueprint.get(
    "/new/<int:sport_id>/<int:return_page>/<int:associates_page>/<int:sign_page>"
)
@token_required
@user_has_permission("signup_new")
def sign_associate_form(sport_id, return_page, associates_page, sign_page):
    """Retorna los asociados para inscribir a una disciplina."""
    sport_ret = sports.get_sport_by_id(sport_id)
    if sport_ret.enabled is False:
        abort(404)
    associates_list = associates.get_unsigned_associated(
        sport_ret, sign_page, setting.get_setting().cant_elements_page
    )

    return render_template(
        "sports/sign_associate.html",
        sport=sport_ret,
        associates=associates_list,
        return_page=return_page,
        associates_page=associates_page,
    )


@signup_blueprint.get("/delete/<int:sport_id>/<int:associate_id>/<int:return_page>")
def delete_signup(sport_id, associate_id, return_page):
    """Elimina una inscripcion."""
    sport = sports.get_sport_by_id(sport_id)
    associate = associates.get_associated_by_id(associate_id)
    sports.delete_singup(sport, associate)
    return redirect(
        url_for(
            "signups.signups_list_page",
            sport_id=sport_id,
            return_page=return_page,
            associates_page=1,
        )
    )

admin/src/web/templates/associates/associated_sports.html
{% extends 'layout.html' %}
{% set active_page = "associates" %}
{% block css %}
<link rel="stylesheet" href="{{ url_for('static',filename='css/sports/sports.css') }}">
{% endblock %}
{% block liks %}
<script src="https://kit.fontawesome.com/e480f6dd1b.js" crossorigin="anonymous"></script>
{% endblock %}
{% block title %}
<title>Disciplinas</title>
{% endblock %}

{% block content %}

<table class="tabla">
    <caption>
        <h1 class="nom-pagina">Lista de disciplinas:</h1>
    </caption>
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Categorias</th>
            <th>Instructores</th>
            <th>Horarios</th>
            <th>Costo mensual</th>
            <th>Borrar</th>
        </tr>
    </thead>
    <tbody>
        {% if sports %}
        {% for sport in sports %}
        <tr>
            <td>{{ sport.name }}</td>
            <td>{{ sport.division }}</td>
            <td>{{ sport.instructors_names }}</td>
            <td>{{ sport.schedule }}</td>
            <td>{{ sport.monthly_fee }} {{ currency }}</th>
            <td>
                <a class="btn btn-eliminar"
                    href="{{ url_for('associates.delete_signup', sport_id=sport.id, associate_id=associated_id, return_page=current_page) }}"
                    onclick="return confirm('¿Quiere eliminar la inscripcion?')">Borrar</a>
            </td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td></td>
            <td></td>
            <td>No hay disciplinas</td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        {% endif %}
    </tbody>
</table>

{% endblock %}

admin/src/web/templates/associates/associates.html
{% extends 'layout.html' %}
{% set active_page = "associates" %}
{% block css %}
<link rel="stylesheet" href="{{ url_for('static',filename='css/associates/associates.css') }}">
{% endblock %}
{% block liks %}
<script src="https://kit.fontawesome.com/e480f6dd1b.js" crossorigin="anonymous"></script>
{% endblock%}
{% block title %}
<title>Asociados</title>
{% endblock %}

{% block content %}

<table id="tableAsociated" class="tabla">
    <caption>
        <div class="div-titulo-buscar">
            <h1 class="nom-pagina">Listado de asociados:</h1>
            <div class="div-buscar">
                <form class="buscar" action="{{ url_for('associates.filtrar')}}" method="POST">
                    <select class="select-estado" name="estado">
                        <option value="all">Estado</option>
                        <option value="activo">Activo</option>
                        <option value="bloqueado">No-activo</option>
                    </select>
                    <input class="buscar_email" name="surname" placeholder="Ingrese el apellido">
                    <button class="boton-filtrar" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
                </form>
            </div>
        </div>
    </caption>
    <thead>
        <tr>
            <th># socio</th>
            <th>Nombre</th>
            <th>Apellido</th>
            <th># documento</th>
            <th>Tipo</th>
            <th>Género</th>
            <th>Dirección</th>
            <th>Estado</th>
            <th>Telefono</th>
            <th>Email</th>
            <th>Fecha de alta</th>
            <th>Editar</th>
            <th>Bloquear</th>
            <th>Eliminar</th>
            <th>Carnet</th>
        </tr>
    </thead>
    <tbody>
        {% for associated in associates.items %}
        <td>{{ associated.id }}</td>
        <td>{{ associated.name }}</td>
        <td>{{ associated.surname }}</td>
        <td>{{ associated.document_number }}</td>
        <td>{{ associated.document_type }}</td>
        <td>{{ associated.gender }}</td>
        <td>{{ associated.direction }}</td>
        <td>{{ associated.condition }}</td>
        {% if associated.phone %}
        <td>{{ associated.phone }}</td>
        {% else %}
        <td>-</td>
        {% endif %}
        {% if associated.mail %}
        <td>{{ associated.mail }}</td>
        {% else %}
        <td>-</td>
        {% endif %}
        <td>{{ associated.discharge_date.strftime('%d-%m-%Y') }}</td>
        <td>
            <a class="btn btn-detalle"
                href="{{ url_for('associates.associated_detail', associated_id=associated.id, current_page = associates.page) }}">Detalle</a>
        </td>
        <td>
            {% if associated.condition == "Activo" %}
            <a class="btn btn-bloquear"
                href="{{ url_for('associates.toggle_enable_associated_by_id', associated_id = associated.id, current_page = associates.page) }}"
                onclick="return confirm('¿Esta seguro? Si hay inscripciones en este asociado seran eliminadas')">
                Deshabilitar</a>
            {% else %}
            <a class="btn btn-bloquear"
                href="{{ url_for('associates.toggle_enable_associated_by_id', associated_id = associated.id, current_page = associates.page) }}">
                Habilitar</a>
            {% endif %}
            </a>
        </td>
        <td>
            <a class="btn btn-eliminar"
                href="{{ url_for('associates.delete_associated_by_id', associated_id=associated.id, current_page = associates.page) }}"
                onclick="return confirm('¿Quiere eliminar el asociado?')">Eliminar</a>
        </td>
        <td>
            {% if associated.credential %}
            <a class="btn btn-credential"
                href="{{ url_for('associates.associated_license', associated_id = associated.id, current_page = associates.page) }}">
                Ver Carnet</a>
            {% else %}
            <a class="btn btn-credential"
                href="{{ url_for('associates.new_credential_form', associated_id = associated.id, current_page = associates.page) }}">
                Generar Carnet </a>
            {% endif %}
        </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<table id="tablePdf" class="tabla-asociados" style="display: none;color: white;">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Apellido</th>
            <th>Tipo de documento</th>
            <th>Numero de documento</th>
            <th>Género</th>
            <th>Dirección</th>
            <th>Estado</th>
            <th>Telefono</th>
            <th>Email</th>
            <th>Fecha de alta</th>
        </tr>
    </thead>
    <tbody>
        {% if associates.items %}
        {% for associated in associates.items %}
        <tr>
            <td>{{ associated.name }}</td>
            <td>{{ associated.surname }}</td>
            <td>{{ associated.document_type }}</td>
            <td>{{ associated.document_number }}</td>
            <td>{{ associated.gender }}</td>
            <td>{{ associated.direction }}</td>
            <td>{{ associated.condition }}</td>
            <td>{{ associated.phone }}</td>
            <td>{{ associated.mail }}</td>
            <td>{{ associated.discharge_date.strftime('%d-%m-%Y') }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>No hay asociados</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        {% endif %}
    </tbody>
</table>

<div class="paginacion">
    <ul>
        {% if associates.has_prev %}
        <li>
            <a {% if filterState[0] %} {% if filterState[1]=="apellido" %}
                href="{{ url_for('associates.filtrarApellido', surname = filterState[2], num = associates.prev().page) }}"
                {% elif filterState[1]=="estado" %}
                href="{{ url_for('associates.filtrarEstado', estado = filterState[3], num = associates.prev().page) }}"
                {% else %}
                href="{{ url_for('associates.filtrarApellidoEstado', estado = filterState[3], surname = filterState[2], num = associates.prev().page) }}"
                {% endif %} {% else %}
                href="{{ url_for('associates.associated_index_page', num=associates.prev().page) }}" {% endif %}><i
                    class="fas fa-chevron-left"></i></a>
        </li>
        {% endif %}
        {% for page_num in range(associates.pages) %}
        {% if page_num + 1 > associates.page - 3 and page_num + 1 < associates.page + 3 %} {% if page_num +
            1==associates.page %} <li>
            <a class="active">{{page_num + 1}}</a>
            </li>
            {% else %}
            <li>
                <a {% if filterState[0] %} {% if filterState[1]=="apellido" %}
                    href="{{ url_for('associates.filtrarApellido', surname = filterState[2], num = page_num + 1) }}" {%
                    elif filterState[1]=="estado" %}
                    href="{{ url_for('associates.filtrarEstado', estado = filterState[3], num = page_num + 1) }}" {%
                    else %}
                    href="{{ url_for('associates.filtrarApellidoEstado', estado = filterState[3], surname = filterState[2], num = page_num + 1) }}"
                    {% endif %} {% else %} href="{{ url_for('associates.associated_index_page', num = page_num + 1) }}"
                    {% endif %}>
                    {{page_num + 1}}</a>
            </li>
            {% endif %}
            {% endif %}
            {% endfor %}
            {% if associates.has_next %}
            <li>
                <a {% if filterState[0] %} {% if filterState[1]=="apellido" %}
                    href="{{ url_for('associates.filtrarApellido', surname = filterState[2], num = associates.next().page) }}"
                    {% elif filterState[1]=="estado" %}
                    href="{{ url_for('associates.filtrarEstado', estado = filterState[3], num = associates.next().page) }}"
                    {% else %}
                    href="{{ url_for('associates.filtrarApellidoEstado', estado = filterState[3], surname = filterState[2], num = associates.next().page) }}"
                    {% endif %} {% else %}
                    href="{{ url_for('associates.associated_index_page', num = associates.next().page) }}" {% endif %}>
                    <i class="fas fa-chevron-right"></i></a>
            </li>
            {% endif %}
    </ul>
</div>
<div class="div-btn">
    <div class="div-btn-columna">
        <a id=boton-agregar-asociado
            href="{{ url_for('associates.new_associated_form', current_page = associates.page) }}">Agregar Asociado</a>
        <button id="pdfExport" onclick="javascript:exportPDF();">Export PDF</button>
        <button id="csvExport" onclick="javascript:exportCSV();">Export CSV</button>
    </div>
</div>

<script src="{{ url_for('static',filename='js/TableCSVExporter.js') }}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.4.1/jspdf.debug.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/0.4.1/html2canvas.js"></script>

<script>
    function exportPDF() {

        const table = document.getElementById('tableAsociated');
        const tablePdf = document.getElementById('tablePdf');

        table.style.display = "none";
        tablePdf.style.display = "block";

        html2canvas(tablePdf, {
            onrendered: function (canvasObj) {
                var pdf = new jsPDF({
                    orientation: "landscape",
                    unit: "in",
                    format: [16, 9]
                }),
                    pdfConf = {
                        pagesplit: false,
                        backgroundColor: '#FFF'
                    };
                document.body.appendChild(canvasObj); //appendChild is required for html to add page in pdf
                pdf.addHTML(canvasObj, 0, 0, pdfConf, function () {
                    document.body.removeChild(canvasObj);
                    //pdf.addPage();
                    table.style.display = "block";
                    tablePdf.style.display = "none";
                    pdf.save('asociados.pdf');
                    window.location.reload()
                });
            }
        });
    }

    function exportCSV() {
        const dataTable = document.getElementById('tablePdf');

        const exporter = new TableCSVExporter(dataTable);
        const csvOutput = exporter.convertToCSV();
        const csvBlob = new Blob([csvOutput], { type: "text/csv" });
        const blobUrl = URL.createObjectURL(csvBlob);
        const anchorElement = document.createElement("a");

        anchorElement.href = blobUrl;
        anchorElement.download = "asociados.csv";
        anchorElement.click();

        setTimeout(() => {
            URL.revokeObjectURL(blobUrl);
        }, 500);
    }

</script>

{% endblock %}

admin/src/web/templates/associates/new_associated.html
{% extends 'layout.html' %}
{% set active_page = "associates" %}
{% block css %}
<link rel="stylesheet" href="{{ url_for('static',filename='css/associates/new_associated.css') }}">
{% endblock %}
{% block title %}
<title>Detalle Asociado</title>
{% endblock %}

{% block nav %}
{{super()}}
{% endblock %}
{% block content %}
<div class="div-form">
    <h2>Nuevo Asociado</h2>
    <form id="for-box" action="{{ url_for('associates.add_associated', current_page=return_page)}}" method="post">
        <label class="labelNombre">Nombre:</label>
        <input class="inputNombre" type="text" id="name" name="name" placeholder="Ingrese el nombre" {% if params %}
            value="{{ params['name'].strip()  }}" {% endif %} autocomplete="off" required>
        <label class="labelApellido">Apellido:</label>
        <input class="inputApellido" type="text" id="surname" name="surname" placeholder="Ingrese el apellido" {% if
            params %} value="{{ params['surname'].strip()  }}" {% endif %} autocomplete="off" required>
        <label class="labelTipoDoc">Tipo de documento:</label>
        <div class="div-select">
            <select class="selectTipoDoc" name="document_type" id="document_type">
                <option value="DNI">DNI</option>
                <option value="LE">LE</option>
                <option value="LC">LC</option>
            </select>
        </div>
        <label class="labelDoc">Numero de documento:</label>
        <input class="inputDoc" type="text" id="document_number" name="document_number"
            placeholder="Ingrese el documento" {% if params %} value="{{ params['document_number'].strip()  }}" {% endif
            %} autocomplete="off" required>
        <label class="labelGenero">Género:</label>
        <div class="div-select">
            <select class="selectGenero" name="gender" id="gender">
                <option value="M">M</option>
                <option value="F">F</option>
                <option value="Otro">Otro</option>
            </select>
        </div>
        <label class="labelDire">Dirección:</label>
        <input class="inputDire" type="text" id="direction" name="direction" placeholder="Ingrese la dirección" {% if
            params %} value="{{ params['direction'].strip()  }}" {% endif %} autocomplete="off" required>
        <label class="labelEstado">Estado:</label>
        <div class="div-select">
            <select class="selectEstado" name="condition" id="condition">
                <option value="Activo">Activo</option>
                <option value="No-activo">no-activo</option>
            </select>
        </div>
        <label class="labelTel">Teléfono:</label>
        <input class="inputTel" type="text" id="phone" name="phone" placeholder="Ingrese el teléfono" {% if params %}
            value="{{ params['phone'].strip()  }}" {% endif %} autocomplete="off">
        <label class="labelEmail">Email:</label>
        <input class="inputEmail" type="email" id="mail" name="mail" placeholder="Ingrese el email" {% if params %}
            value="{{ params['email'].strip()  }}" {% endif %} autocomplete="off">
        <input class="botonAgregar" type="submit" value="Agregar asociado">
        <a class="botonCancelar" href="{{ url_for('associates.associated_index_page', num=return_page) }}">Cancelar</a>
    </form>
</div>


{% endblock %}

admin/src/web/templates/associates/new_credential_associated.html
{% extends 'layout.html' %}
{% set active_page = "associates" %}
{% block css %}
<link rel="stylesheet" href="{{ url_for('static',filename='css/associates/edit_associated.css') }}">
{% endblock %}
{% block title %}
<title>Generar Carnet</title>
{% endblock %}

{% block nav %}
{{super()}}
{% endblock %}
{% block content %}

<div>
    <h2>Crear carnet de asociado </h2>
    <form id="for-box"
        action="{{ url_for('associates.create_credential', associated_id = associated.id, current_page = return_page)}}"
        method="POST" enctype="multipart/form-data" autocomplete="off">
        <label class="labelNombre">Imagen:</label>
        <input type="file", name="archivo", required accept=".png, .jpg, .jpeg">
        <input class="botonAgregar" type="submit" value="Crear carnet">
        <a class="botonCancelar"
            href="{{ url_for('associates.associated_index_page', num = return_page) }}">Cancelar</a>
    </form>
</div>
{% endblock %}