admin/src/web/controllers/signups.py
from flask import Blueprint, render_template, redirect, url_for, abort, flash

from src.core import setting
from src.core import sports
from src.core import associates
from src.core import setting
from src.web.helpers.auth import token_required, user_has_permission

signup_blueprint = Blueprint("signups", __name__, url_prefix="/inscripciones")


# Fuera de uso
# @signup_blueprint.get("/<int:sport_id>/<int:current_page>")
# @token_required
# @user_has_permission("signup_list")
# def signups_list(sport_id, current_page):
#     """Trae todos los inscriptos a una disciplina."""
#     sport_ret = sports.get_sport_by_id(sport_id)
#     return render_template(
#         "sports/signedup.html",
#         associates=sport_ret.associates,
#         sport_id=sport_id,
#         return_page=current_page,
#     )


@signup_blueprint.get("/<int:sport_id>/<int:return_page>/<int:associates_page>")
@token_required
@user_has_permission("signup_list")
def signups_list_page(sport_id, return_page, associates_page):
    """Trae los inscriptos a una disciplina paginados."""
    sport_ret = sports.get_sport_by_id(sport_id)
    associates_ret = associates.get_signed_associated(
        sport_ret, associates_page, setting.get_setting().cant_elements_page
    )
    return render_template(
        "sports/signedup.html",
        associates=associates_ret,
        sport_id=sport_id,
        return_page=return_page,
        associates_page=associates_page,
    )


@signup_blueprint.get(
    "/<int:sport_id>/<int:associate_id>/<int:return_page>/<int:associates_page>/<int:sign_page>"
)
@token_required
@user_has_permission("signup_new")
def sign_associate(sport_id, associate_id, return_page, associates_page, sign_page):
    """Inscribe un asociado a una discplina."""
    sport_ret = sports.get_sport_by_id(sport_id)
    sign = True
    if sport_ret.enabled is False:
        abort(404)

    associate_ret = associates.get_associated_by_id(associate_id)
    if associate_ret.condition == "No-activo":
        flash("El associado no esta activo.", "error")
        sign = False

    if associates.is_defaulter(associate_id):
        flash("El associado es moroso.", "error")
        sign = False

    if sport_ret in associate_ret.sports:
        flash("El associado ya se encuentra inscripto.", "error")
        sign = False

    if sign:
        sports.append_to_associates(sport_ret, associate_ret)
        flash("Inscripcion ralizada", "success")

    return redirect(
        url_for(
            "signups.sign_associate_form",
            sport_id=sport_id,
            return_page=return_page,
            associates_page=associates_page,
            sign_page=sign_page,
        )
    )


@signup_blueprint.get(
    "/new/<int:sport_id>/<int:return_page>/<int:associates_page>/<int:sign_page>"
)
@token_required
@user_has_permission("signup_new")
def sign_associate_form(sport_id, return_page, associates_page, sign_page):
    """Retorna los asociados para inscribir a una disciplina."""
    sport_ret = sports.get_sport_by_id(sport_id)
    if sport_ret.enabled is False:
        abort(404)
    associates_list = associates.get_unsigned_associated(
        sport_ret, sign_page, setting.get_setting().cant_elements_page
    )

    return render_template(
        "sports/sign_associate.html",
        sport=sport_ret,
        associates=associates_list,
        return_page=return_page,
        associates_page=associates_page,
    )


@signup_blueprint.get("/delete/<int:sport_id>/<int:associate_id>/<int:return_page>")
def delete_signup(sport_id, associate_id, return_page):
    """Elimina una inscripcion."""
    sport = sports.get_sport_by_id(sport_id)
    associate = associates.get_associated_by_id(associate_id)
    sports.delete_singup(sport, associate)
    return redirect(
        url_for(
            "signups.signups_list_page",
            sport_id=sport_id,
            return_page=return_page,
            associates_page=1,
        )
    )

admin/src/web/controllers/sports.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, abort

from src.core import sports
from src.core import setting
from src.web.helpers.auth import token_required, user_has_permission

sport_blueprint = Blueprint("sports", __name__, url_prefix="/disciplinas")


@sport_blueprint.get("/")
@token_required
@user_has_permission("users_index")
def sport_index():
    """Obtiene y muestra todas las discplinas."""
    sports_list = sports.list_sports()
    return render_template("sports/sports.html", sports=sports_list)


@sport_blueprint.get("/<int:num>")
@token_required
@user_has_permission("sports_index")
def sport_index_page(num):
    """Trae disciplinas paginadas."""
    sports_list = sports.list_sports_page(num, setting.get_setting().cant_elements_page)
    return render_template(
        "sports/sports.html",
        sports=sports_list,
        currency=setting.get_setting().currency_type,
    )


@sport_blueprint.post("/filtered/<int:num>")
@token_required
@user_has_permission("sports_index")
def sport_index_page_filter(num):
    """Procesa parametros y genera request de filtrado."""
    params = request.form
    if params["estado"] == "habilitada":
        enabled = True
    elif params["estado"] == "deshabilitada":
        enabled = False
    else:
        enabled = "None"

    if params["name"] != "":
        name = params["name"]
    else:
        name = "None"

    return redirect(
        url_for("sports.sport_index_page_filtered", num=num, name=name, enabled=enabled)
    )


@sport_blueprint.get("/filtered/<int:num>/<name>/<enabled>")
@token_required
@user_has_permission("sports_index")
def sport_index_page_filtered(num, name, enabled):
    """Filtra segun los parametros y devuelve disciplinas paginadas."""
    if name == "None":
        name = None

    if enabled == "None":
        enabled = None

    sports_list = sports.list_sports_page_filtered(
        num, setting.get_setting().cant_elements_page, enabled, name
    )

    return render_template(
        "sports/sports.html",
        sports=sports_list,
        currency=setting.get_setting().currency_type,
        filters={"name": str(name), "enabled": str(enabled)},
    )


# No funciona por ahora
# @sport_blueprint.get("/detalle/<sport_id>")
# @token_required
# @user_has_permission("sports_show")
# def view(sport_id):
#     """Obtiene y muestra una discplina."""
#     sport = sports.get_sport_by_id(sport_id)
#     return render_template("sports/sports.html", sports=[sport])


@sport_blueprint.get("/new/<int:current_page>")
@token_required
@user_has_permission("sports_new")
def new_sport_form(current_page):
    """Muestra formulario para agregar una disciplina."""
    return render_template("sports/new_sport.html", return_page=current_page)


@sport_blueprint.post("/new/<int:current_page>")
@token_required
@user_has_permission("sports_new")
def add_sport(current_page):
    """Recibe datos y crea una nueva discplina. Luego Redirecciona."""
    params = request.form
    enable = True
    if request.form.get("enabled") is None:
        enable = False

    result = sports.verify_new_sport(params, enable)
    if not result["sport"]:
        flash(result["message"], "error")
        # return redirect(url_for("sports.new_sport_form"))
        return render_template(
            "sports/new_sport.html", placeholder=params, return_page=current_page
        )

    flash(result["message"], "success")
    return redirect(url_for("sports.sport_index_page", num=current_page))


@sport_blueprint.get("/delete/<sport_id>/<int:current_page>")
@token_required
@user_has_permission("sports_destroy")
def delete_sport_by_id(sport_id, current_page):
    """Recibe una id de disciplina y la elimina de la BD."""
    sport_to_delete = sports.get_sport_by_id(sport_id)
    if sport_to_delete.associates:
        message = "La disciplina tiene inscriptos"
        flash(message, "error")
        return redirect(url_for("sports.sport_index_page", num=current_page))

    sports.delete_sport(sport_to_delete)
    message = "Disciplinas eliminada correctamente"
    flash(message, "success")
    # Como vuelvo a la pagina en la que estaba si la pagina se elimino?
    return redirect(url_for("sports.sport_index_page", num=1))


@sport_blueprint.get("/toggle/<int:sport_id>/<int:current_page>")
@token_required
@user_has_permission("sports_update")
def toggle_enable_sport_by_id(sport_id, current_page):
    """Recibe una id de sport e invierte "habilitado"."""
    sport = sports.get_sport_by_id(sport_id)
    sports.delete_all_signed(sport)
    sports.invert_sport_enabled(sport)
    sports.update_sport(sport)
    return redirect(url_for("sports.sport_index_page", num=current_page))


@sport_blueprint.get("/update/<sport_id>/<int:current_page>")
@token_required
@user_has_permission("sports_update")
def update_sport_form(sport_id, current_page):
    """Muetra el formulario para actualizar la informacion de una disciplina."""
    sport = sports.get_sport_by_id(sport_id)
    return render_template(
        "sports/edit_sport.html", sport=sport, return_page=current_page
    )


@sport_blueprint.post("/update/<sport_id>/<int:current_page>")
@token_required
@user_has_permission("sports_update")
def update_sport(sport_id, current_page):
    """Actualiza los valores de la disciplina y redirecciona."""
    sport = sports.get_sport_by_id(sport_id)
    params = request.form
    result = sports.verify_edit_sport(params, sport)
    if not result["success"]:
        flash(result["message"], "error")
        return render_template(
            "sports/edit_sport.html", sport=sport, return_page=current_page
        )

    sport.name = params["sportName"]
    sport.division = params["division"]
    sport.instructors_names = params["instructors"]
    sport.schedule = params["schedule"]
    sport.monthly_fee = params["fee"].replace(".", "")
    sports.update_sport(sport)

    flash(result["message"], "success")
    return redirect(url_for("sports.sport_index_page", num=current_page))

admin/src/web/templates/sports/edit_sport.html
{% extends 'layout.html' %}
{% set active_page = "sports" %}
{% block css %}
<link rel="stylesheet" href="{{ url_for('static',filename='css/sports/new_sport.css') }}">
{% endblock %}
{% block title %}
<title>Editar disciplina</title>
{% endblock %}

{% block nav %}
{{super()}}
{% endblock %}
{% block content %}

<div class="div-form">
    <h2>Actualizar Disciplina</h2>
    <form id="for-box" action="{{ url_for('sports.update_sport', sport_id=sport.id, current_page=return_page)}}"
        method="post">
        <label class="labelNombre">Nombre:</label>
        <input class="inputNombre" maxlength="50" type="text" id="sportName" name="sportName" placeholder="Ingrese el nombre" {% if
            sport %} value="{{ sport.name }}" maxlength="50" {% endif %} autocomplete="off" required>
        <label class="labelDivision">Division:</label>
        <input class="inputDivision" maxlength="50" type="text" id="division" name="division" placeholder="Ingrese la división" {% if
            sport %} value="{{ sport.division }}" maxlength="50" {% endif %} autocomplete="off" required>
        <label class="labelInstructores">Instructores:</label>
        <input class="inputInstructores" maxlength="300" type="text" id="instructors" name="instructors"
            placeholder="Ingrese los instructores" maxlength="50" {% if sport %} value="{{ sport.instructors_names }}" {% endif %}
            required>
        <label class="labelHorarios">Horarios:</label>
        <input class="inputHorarios" maxlength="300" type="text" id="schedule" name="schedule" placeholder="Ingrese el horario" {% if
            sport %} value="{{ sport.schedule }}" maxlength="50" {% endif %} required>
        <label class="labelCuota">Cuota:</label>
        <input class="inputCuota" maxlength="10" type="text" id="fee" name="fee" placeholder="Ingrese el valor de la cuota" {% if sport
            %} value="{{ sport.monthly_fee }}" {% endif %} required>
        <input class="botonAgregar" type="submit" value="Actualizar disciplina">
        <a class="botonCancelar" href="{{ url_for('sports.sport_index_page', num=return_page) }}">Volver</a>
    </form>
</div>

{% endblock %}

admin/src/web/templates/sports/new_sport.html
{% extends 'layout.html' %}
{% set active_page = "sports" %}
{% block css %}
<link rel="stylesheet" href="{{ url_for('static',filename='css/sports/new_sport.css') }}">
{% endblock %}
{% block title %}
<title>Detalle disciplina</title>
{% endblock %}

{% block nav %}
{{super()}}
{% endblock %}
{% block content %}

<div class="div-form">
    <h2>Nueva Disciplina</h2>
    <form id="for-box" action="{{ url_for('sports.add_sport', current_page=return_page)}}" method="post">
        <label class="labelNombre">Nombre:</label>
        <input class="inputNombre" maxlength="50" type="text" id="sportName" name="sportName" placeholder="Ingrese el nombre" {% if
            placeholder %} value="{{ placeholder['sportName'].strip()  }}" maxlength="50" {% endif %} autocomplete="off" required>
        <label class="labelDivision">Division:</label>
        <input class="inputDivision" maxlength="50" type="text" id="division" name="division" placeholder="Ingrese la división" {% if
            placeholder %} value="{{ placeholder['division'].strip()  }}" maxlength="50" {% endif %} autocomplete="off" required>
        <label class="labelInstructores">Instructores:</label>
        <input class="inputInstructores" maxlength="300" type="text" id="instructors" name="instructors"
            placeholder="Ingrese los instructores" maxlength="50" {% if placeholder %}
            value="{{ placeholder['instructors'].strip()  }}" maxlength="50" {% endif %} required>
        <label class="labelHorarios">Horarios:</label>
        <input class="inputHorarios" maxlength="300" type="text" id="schedule" name="schedule" placeholder="Ingrese el horario" {% if
            placeholder %} value="{{ placeholder['schedule'].strip()  }}" maxlength="50" {% endif %} required>
        <label class="labelCuota">Cuota:</label>
        <input class="inputCuota" maxlength="10" type="text" id="fee" name="fee" placeholder="Ingrese el valor de la cuota" {% if
            placeholder %} value="{{ placeholder['fee'].strip()  }}" {% endif %} required>
        <label class="labelHabilitado">Habilitado:</label>
        <input class="checkboxHabilitado" type="checkbox" id="enabled" name="enabled">
        <input class="botonAgregar" type="submit" value="Agregar disciplina">
        <a class="botonCancelar" href="{{ url_for('sports.sport_index_page', num=return_page) }}">Volver</a>
    </form>
</div>

{% endblock %}

admin/src/web/templates/sports/sign_associate.html
{% extends 'layout.html' %}
{% set active_page = "sports" %}
{% block css %}
<link rel="stylesheet" href="{{ url_for('static',filename='css/sports/sports.css') }}">
{% endblock %}
{% block liks %}
<script src="https://kit.fontawesome.com/e480f6dd1b.js" crossorigin="anonymous"></script>
{% endblock %}
{% block title %}
<title>Inscribir</title>
{% endblock %}

{% block content %}


<table class="tabla">
    <caption>
        <h1 class="nom-pagina">Inscribir a {{ sport.name }} {{ sport.division }}</h1>
    </caption>
    <thead>
        <tr>
            <th># socio</th>
            <th>Nombre</th>
            <th>Apellido</th>
            <th>Tipo de documento</th>
            <th>Numero de documento</th>
            <th>Genero</th>
            <th>Estado</th>
            <th>Telefono</th>
            <th>Email</th>
            <th>Fecha de alta</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% if associates %}
        {% for associated in associates.items %}
        <td>{{ associated.id }}</td>
        <td>{{ associated.name }}</td>
        <td>{{ associated.surname }}</td>
        <td>{{ associated.document_type }}</td>
        <td>{{ associated.document_number }}</td>
        <td>{{ associated.gender }}</td>
        <td>{{ associated.condition }}</td>
        {% if associated.phone %}
        <td>{{ associated.phone }}</td>
        {% else %}
        <td>-</td>
        {% endif %}
        {% if associated.mail %}
        <td>{{ associated.mail }}</td>
        {% else %}
        <td>-</td>
        {% endif %}
        <td>{{ associated.discharge_date.strftime('%d-%m-%Y') }}</td>
        <td>
            <a class="btn btn-detalle"
                href="{{ url_for('signups.sign_associate', sport_id=sport.id, associate_id=associated.id, return_page=return_page, associates_page=associates_page, sign_page=associates.page) }}">Inscribir</a>
        </td>
        </tr>
        {% endfor %}
        {% else %}
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th>Sin Asociados</th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        {% endif %}
    </tbody>
</table>

<div class="paginacion">
    <ul>
        {% if associates.has_prev %}
        <li>
            <a
                href="{{ url_for('signups.sign_associate_form', sport_id=sport.id, return_page=return_page, associates_page=associates_page, sign_page=associates.prev().page) }}"><i
                    class="fas fa-chevron-left"></i></a>
        </li>
        {% endif %}
        {% for page_num in range(associates.pages) %}
        {% if page_num + 1 > associates.page - 3 and page_num + 1 < associates.page + 3 %} {% if page_num +
            1==associates.page %} <li>
            <a class="active">{{page_num + 1}}</a>
            </li>
            {% else %}
            <li>
                <a
                    href="{{ url_for('signups.sign_associate_form', sport_id=sport.id, return_page=return_page, associates_page=associates_page, sign_page=page_num + 1) }}">{{page_num
                    + 1}}</a>
            </li>
            {% endif %}
            {% endif %}
            {% endfor %}
            {% if associates.has_next %}
            <li>
                <a
                    href="{{ url_for('signups.sign_associate_form', sport_id=sport.id, return_page=return_page, associates_page=associates_page, sign_page=associates.next().page) }}">
                    <i class="fas fa-chevron-right"></i></a>
            </li>
            {% endif %}
    </ul>
</div>

<div class="div-btn">
    <a class="botonCancelar"
        href="{{ url_for('signups.signups_list_page', sport_id=sport.id, return_page=return_page, associates_page=associates_page) }}">Volver</a>
</div>


{% endblock %}

admin/src/web/templates/sports/signedup.html
{% extends 'layout.html' %}
{% set active_page = "sports" %}
{% block css %}
<link rel="stylesheet" href="{{ url_for('static',filename='css/sports/sports.css') }}">
{% endblock %}
{% block liks %}
<script src="https://kit.fontawesome.com/e480f6dd1b.js" crossorigin="anonymous"></script>
{% endblock %}
{% block title %}
<title>Inscriptos</title>
{% endblock %}

{% block content %}



<table class="tabla">
    <caption>
        <h1 class="nom-pagina">Inscriptos</h1>
    </caption>
    <thead>
        <tr>
            <th># socio</th>
            <th>Nombre</th>
            <th>Apellido</th>
            <th>Tipo de documento</th>
            <th>Numero de documento</th>
            <th>Genero</th>
            <th>Direccion</th>
            <th>Estado</th>
            <th>Telefono</th>
            <th>Email</th>
            <th>Fecha de alta</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% if associates %}
        {% for associated in associates.items %}
        <td>{{ associated.id }}</td>
        <td>{{ associated.name }}</td>
        <td>{{ associated.surname }}</td>
        <td>{{ associated.document_type }}</td>
        <td>{{ associated.document_number }}</td>
        <td>{{ associated.gender }}</td>
        <td>{{ associated.direction }}</td>
        <td>{{ associated.condition }}</td>
        {% if associated.phone %}
        <td>{{ associated.phone }}</td>
        {% else %}
        <td>-</td>
        {% endif %}
        {% if associated.mail %}
        <td>{{ associated.mail }}</td>
        {% else %}
        <td>-</td>
        {% endif %}
        <td>{{ associated.discharge_date.strftime('%d-%m-%Y') }}</td>
        <td>
            <a class="btn btn-eliminar"
                href="{{ url_for('signups.delete_signup', sport_id=sport_id, associate_id=associated.id, return_page=return_page) }}"
                onclick="return confirm('¿Eliminar la inscripcion?')">Eliminar</a>
        </td>
        </tr>
        {% endfor %}
        {% else %}
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th>Sin Inscriptos</th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        <th></th>
        {% endif %}
    </tbody>
</table>

<div class="paginacion">
    <ul>
        {% if associates.has_prev %}
        <li>
            <a
                href="{{ url_for('signups.signups_list_page', sport_id=sport_id, return_page=return_page, associates_page=associates.prev().page) }}"><i
                    class="fas fa-chevron-left"></i></a>
        </li>
        {% endif %}
        {% for page_num in range(associates.pages) %}
        {% if page_num + 1 > associates.page - 3 and page_num + 1 < associates.page + 3 %} {% if page_num +
            1==associates.page %} <li>
            <a class="active">{{page_num + 1}}</a>
            </li>
            {% else %}
            <li>
                <a
                    href="{{ url_for('signups.signups_list_page', sport_id=sport_id, return_page=return_page, associates_page=page_num + 1) }}">{{page_num
                    + 1}}</a>
            </li>
            {% endif %}
            {% endif %}
            {% endfor %}
            {% if associates.has_next %}
            <li>
                <a
                    href="{{ url_for('signups.signups_list_page', sport_id=sport_id, return_page=return_page, associates_page=associates.next().page) }}">
                    <i class="fas fa-chevron-right"></i></a>
            </li>
            {% endif %}
    </ul>
</div>

<div class="div-btn">
    <a id="boton-agregar-disciplina"
        href="{{ url_for('signups.sign_associate_form', sport_id=sport_id, return_page=return_page, associates_page=associates_page, sign_page=1) }}">Inscribir</a>

    <a class="botonCancelar" href="{{ url_for('sports.sport_index_page', num=return_page) }}">Volver</a>
</div>


{% endblock %}

admin/src/web/templates/sports/sports.html
{% extends 'layout.html' %}
{% set active_page = "sports" %}
{% block css %}
<link rel="stylesheet" href="{{ url_for('static',filename='css/sports/sports.css') }}">
{% endblock %}
{% block liks %}
<script src="https://kit.fontawesome.com/e480f6dd1b.js" crossorigin="anonymous"></script>
{% endblock %}
{% block title %}
<title>Disciplinas</title>
{% endblock %}

{% block content %}

<table class="tabla">
    <caption>
        <div class="div-titulo-buscar">
            <h1 class="nom-pagina">Listado de disciplinas:</h1>
            <div class="div-buscar">
                <form class="buscar" action="{{url_for(
                             'sports.sport_index_page_filter',
                             num=1
                             ) }}" method="POST">
                    <select class="select-estado" name="estado">
                        <option value="all">Estado</option>
                        <option value="habilitada">Habilitada</option>
                        <option value="deshabilitada">Deshabilitada</option>
                    </select>
                    <input class="buscar_nombre" name="name" placeholder="Ingrese el nombre">
                    <button class="boton-filtrar" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
                </form>
            </div>
        </div>
    </caption>
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Categorias</th>
            <th>Instructores</th>
            <th>Horarios</th>
            <th>Costo mensual</th>
            <th>Habilitada</th>
            <th>Editar</th>
            <th>Habilitar</th>
            <th>Eliminar</th>
            <th>Inscriptos</th>
        </tr>
    </thead>
    <tbody>
        {% if sports.items %}
        {% for sport in sports.items %}
        <tr>
            <td>{{ sport.name }}</td>
            <td>{{ sport.division }}</td>
            <td>{{ sport.instructors_names }}</td>
            <td>{{ sport.schedule }}</td>
            <td>{{ sport.monthly_fee }} {{ currency }}</th>
                {% if sport.enabled==True %}
            <td>Si</td>
            {% else %}
            <td>No</td>
            {% endif %}
            <td>
                <a class="btn btn-detalle"
                    href="{{ url_for('sports.update_sport_form', sport_id=sport.id, current_page=sports.page) }}">Editar</a>
            </td>
            <td>
                {% if sport.enabled==False %}
                <a class="btn btn-bloquear"
                    href="{{ url_for('sports.toggle_enable_sport_by_id', sport_id=sport.id, current_page=sports.page) }}">
                    Habilitar</a>
                {% else %}
                <a class="btn btn-bloquear"
                    href="{{ url_for('sports.toggle_enable_sport_by_id', sport_id=sport.id, current_page=sports.page) }}"
                    onclick="return confirm('¿Esta seguro? Si hay inscripciones en esta disciplina seran eliminadas')">
                    Deshabilitar</a>
                {% endif %}
            </td>
            <td>
                {% if email_has_permission(session["user"], "sports_destroy") %}
                <a class="btn btn-eliminar"
                    href="{{ url_for('sports.delete_sport_by_id', sport_id=sport.id, current_page=sports.page) }}"
                    onclick="return confirm('¿Quiere eliminar la disciplina?')">Eliminar</a>
            </td>
            {% endif %}
            {% if sport.enabled==True %}
            <td>
                <a id="boton-agregar-disciplina"
                    href="{{ url_for('signups.signups_list_page',sport_id=sport.id , return_page=sports.page, associates_page=1) }}">Ver</a>
            </td>
            {% else %}
            <td></td>
            {% endif %}
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>No hay disciplinas</td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        {% endif %}
    </tbody>
</table>
<div class="paginacion">
    <ul>
        {% if sports.has_prev %}
        <li>
            {% if filters %}
            <a href="{{ url_for(
                     'sports.sport_index_page_filtered',
                     num=sports.prev().page,
                     name=filters.name,
                     enabled=filters.enabled
                     ) }}"><i class="fas fa-chevron-left"></i></a>
            {% else %}
            <a href="{{ url_for('sports.sport_index_page', num=sports.prev().page) }}"><i
                    class="fas fa-chevron-left"></i></a>
            {% endif %}
        </li>
        {% endif %}
        {% for page_num in range(sports.pages) %}
        {% if page_num + 1 > sports.page - 3 and page_num + 1 < sports.page + 3 %} {% if page_num + 1==sports.page %}
            <li>
            <a class="active">{{page_num + 1}}</a>
            </li>
            {% else %}
            <li>
                {% if filters %}
                <a href="{{ url_for(
                             'sports.sport_index_page_filtered',
                             num=page_num + 1,
                             name=filters.name,
                             enabled=filters.enabled
                             ) }}">{{page_num + 1}}</a>
                {% else %}
                <a href="{{ url_for('sports.sport_index_page', num=page_num + 1) }}">{{page_num + 1}}</a>
                {% endif %}
            </li>
            {% endif %}
            {% endif %}
            {% endfor %}
            {% if sports.has_next %}
            <li>
                {% if filters %}
                <a href="{{ url_for('sports.sport_index_page_filtered',
                             num=sports.next().page,
                             name=filters.name,
                             enabled=filters.enabled
                             ) }}">
                    {% else %}
                    <a href="{{ url_for('sports.sport_index_page', num=sports.next().page) }}">
                        {% endif %}
                        <i class="fas fa-chevron-right"></i></a>
            </li>
            {% endif %}
    </ul>
</div>
<div class="div-btn">
    <a id="boton-agregar-disciplina" href="{{ url_for('sports.new_sport_form', current_page=sports.page) }}">Agregar
        disciplina</a>
</div>
{% endblock %}